apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: randomquotes-production
resources:
  - ../../base

secretGenerator:
  - name: random-quotes-secrets
    literals:
      - homepageDisplay="This is prod"

images:
  - name: harrisonmeister/randomquotes-k8s
    newName: harrisonmeister/randomquotes-k8s
    newTag: 0.1.146
