apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: randomquotes-staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: randomquotes
spec:
  project: default
  destination:
    name: in-cluster
    namespace: randomquotes-staging
  source:
    path: k8s/overlays/staging
    repoURL: https://github.com/harrisonmeister/randomquotes-k8s.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
