apiVersion: v1
kind: Secret
metadata:
  name: octopus-tentacle-secret
type: Opaque
stringData:
  apiKey: "YOUR_API_KEY"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tentacle-deployment  
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: octopus-tentacle
  template:
    metadata:
      labels:
        component: octopus-tentacle
    spec:
      containers:
        - name: octopus-tentacle
          image: octopusdeploy/tentacle:8.1.563
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "2500m"
          imagePullPolicy: "Always"
          env:
           - name: ServerApiKey
             valueFrom:
               secretKeyRef:
                 name: octopus-tentacle-secret
                 key: apiKey
           - name: ServerUrl
             value: "YOUR_SERVER_URL"
           - name: Space
             value: "Default"
           - name: TargetWorkerPool
             value: "Local K8s Worker Pool"
           - name: ACCEPT_EULA
             value: "Y"
           - name: DISABLE_DIND
             value: "N"
           - name: ServerPort
             value: "10943"
           - name: TargetName
             value: "K8s Worker"
              