apiVersion: v1
kind: ServiceAccount
metadata:
  name: octopus-svc-account
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: octopus-svc-account-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: octopus-svc-account
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: octopus-svc-account-role
  namespace: default
rules:
  - apiGroups:
        - ""
        - apps
        - autoscaling
        - batch
        - extensions
        - policy
        - "rbac.authorization.k8s.io"
        - "networking.k8s.io"
        - secrets        
    resources:
      - pods
      - componentstatuses
      - configmaps
      - daemonsets
      - deployments
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingress
      - ingresses
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - serviceaccounts
      - services
      - secrets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  octopus-svc-account-role-binding
subjects:
- namespace: default
  kind: ServiceAccount
  name: octopus-svc-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: octopus-svc-account-role