apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomquotes-deployment
  annotations:
    codefresh.io/product: randomquotes
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels: 
      component: randomquotes-web
  template:
    metadata:
      labels:
        component: randomquotes-web
    spec:
      containers:
        - name: randomquotes
          image: harrisonmeister/randomquotes-k8s:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http-port
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: RANDOM_PHRASE
              valueFrom:
                secretKeyRef:
                  name: random-quotes-secrets
                  key: homepageDisplay
