apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: randomquotes-dev
resources:
  - ../../base
secretGenerator:
  - name: random-quotes-secrets
    literals:
      - homepageDisplay="This is dev"
images:
  - name: harrisonmeister/randomquotes-k8s
    newName: harrisonmeister/randomquotes-k8s
    newTag: 20250617.24.1
